const mongoose = require("mongoose");

const { Collections } = require("../common/constants/Collections");
const { Currencies } = require("../common/constants/Currencies");
const { Models } = require("../common/constants/Models");
const { PaymentStatusTypes, PaymentStatus } = require("../common/constants/PaymentStatus");
const { Schema } = mongoose;

const paymentSchemaType = {
  // payment against the order id from the db
  orderId: {
    type: mongoose.Types.ObjectId,
    required: true,
    ref: Models.Order
  },
  // order id generated by third party payment service
  txnOrderId: {
    type: String,
    required: true,
    unique: true
  },
  // payment id generated by third party payment service
  txnPaymentId: {
    type: String
  },
  txnPaymentStatus: {
    type: String,
    enum: PaymentStatusTypes,
    default: PaymentStatus.PENDING
  },
  txnPaymentCompletedAt: {
    type: Date
  },
  amount: {
    type: Number,
    required: true
  },
  currency: {
    type: String,
    required: true,
    default: Currencies.INR
  },
  createdAt: {
    type: Date,
    default: Date.now
  }
};

const paymentSchema = new Schema(paymentSchemaType);
const Payment = mongoose.model(Models.Payment, paymentSchema, Collections.Payment);

module.exports = Payment;
