const mongoose = require("mongoose");
const { PaymentStatusTypes } = require("../common/constants/PaymentStatus");
const { Schema } = mongoose;

const paymentSchemaType = {
  // payment against the order id from the db
  orderId: {
    type: mongoose.Types.ObjectId,
    required: true,
    ref: "Order",
  },
  // order id generated by third party payment service
  txnOrderId: {
    type: String,
    required: true,
  },
  // payment id generated by third party payment service
  txnPaymentId: {
    type: String,
  },
  txnPaymentStatus: {
    type: String,
    enum: PaymentStatusTypes,
  },
  txnPaymentCompletedAt: {
    type: Date,
  },
  totalAmount: {
    type: Number,
    required: true,
  },
  currency: {
    type: String,
    required: true,
    default: "INR",
  },
  createdAt: {
    type: Date,
    default: Date.now(),
  },
};

const paymentSchema = new Schema(paymentSchemaType);
const Payment = mongoose.model("Payment", paymentSchema, "payments");

module.exports = Payment;
